version: '3.8'

services:
  downite:
    build: .
    ports:
      - "4173:4173"
      - "9999:9999"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - downite-network

networks:
  downite-network:
    driver: bridge