version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "4173:4173"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PUBLIC_URL=${PUBLIC_URL:-/}
      - VITE_API_URL=http://${HOST:-localhost}:9999
    networks:
      - downite-network
    labels:
      coolify.enable: true

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "9999:9999"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - downite-network
    labels:
      coolify.enable: true

networks:
  downite-network:
    driver: bridge